
import java.sql.Statement;
import java.lang.Object;
import java.lang.String;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnOgretmenEkle = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txt_OgretmenAdi = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnOgrenciEkle = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        txt_OgrenciAdi = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_Sinif = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cmb_Ogrenci = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cmb_ders = new javax.swing.JComboBox();
        btn_DoldurDers = new javax.swing.JButton();
        btn_DoldurOgrenci = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_derslik = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ad = new javax.swing.JTextArea();
        btnBaglanti = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_kod = new javax.swing.JTextArea();
        cmb_ogretmenListele = new javax.swing.JComboBox();
        btnDoldur = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRaporlama = new javax.swing.JTable();
        cmbRaporla = new javax.swing.JComboBox();
        btnRaporlama = new javax.swing.JButton();
        btnDoldurTablo = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setToolTipText("");

        btnOgretmenEkle.setText("Ekle");
        btnOgretmenEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgretmenEkleActionPerformed(evt);
            }
        });

        txt_OgretmenAdi.setColumns(20);
        txt_OgretmenAdi.setRows(5);
        jScrollPane9.setViewportView(txt_OgretmenAdi);

        jLabel7.setText("Ogretmen Adı");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOgretmenEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnOgretmenEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Öğretmen Ekleme", jPanel2);

        btnOgrenciEkle.setText("Ekle");
        btnOgrenciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrenciEkleActionPerformed(evt);
            }
        });

        txt_OgrenciAdi.setColumns(20);
        txt_OgrenciAdi.setRows(5);
        jScrollPane11.setViewportView(txt_OgrenciAdi);

        jLabel9.setText("Öğrenci Adı");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOgrenciEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane11)
                        .addComponent(btnOgrenciEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Öğrenci Ekleme", jPanel3);

        btn_Sinif.setText("Ekle");
        btn_Sinif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SinifActionPerformed(evt);
            }
        });

        jLabel11.setText("Öğrenci Adı");

        jLabel12.setText("Ders Adı");

        btn_DoldurDers.setText("Doldur");
        btn_DoldurDers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoldurDersActionPerformed(evt);
            }
        });

        btn_DoldurOgrenci.setText("Doldur");
        btn_DoldurOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoldurOgrenciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_DoldurOgrenci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(cmb_Ogrenci, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_DoldurDers)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(cmb_ders, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_Sinif)
                        .addGap(70, 70, 70)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmb_Ogrenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DoldurOgrenci))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmb_ders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DoldurDers))
                .addGap(7, 7, 7)
                .addComponent(btn_Sinif)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ders Seçimi", jPanel4);

        txt_derslik.setColumns(20);
        txt_derslik.setRows(5);
        jScrollPane4.setViewportView(txt_derslik);

        txt_ad.setColumns(20);
        txt_ad.setRows(5);
        jScrollPane2.setViewportView(txt_ad);

        btnBaglanti.setText("Ekle");
        btnBaglanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaglantiActionPerformed(evt);
            }
        });

        jLabel1.setText("Ogretmen ID");

        jLabel2.setText("Ders Adı");

        jLabel3.setText("Ders Kodu");

        jLabel4.setText("Dönem");

        txt_kod.setColumns(20);
        txt_kod.setRows(5);
        jScrollPane3.setViewportView(txt_kod);

        btnDoldur.setText("Doldur");
        btnDoldur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoldurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBaglanti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_ogretmenListele, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoldur)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmb_ogretmenListele, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBaglanti))
                    .addComponent(btnDoldur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ders Ekleme", jPanel1);

        tableRaporlama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tableRaporlama);

        btnRaporlama.setText("Raporla");
        btnRaporlama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaporlamaActionPerformed(evt);
            }
        });

        btnDoldurTablo.setText("Doldur");
        btnDoldurTablo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoldurTabloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRaporla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnDoldurTablo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRaporlama, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbRaporla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRaporlama)
                    .addComponent(btnDoldurTablo))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Raporlama", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Ders Ekleme");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JPanel contentPane;
	private JTable table;
	DefaultTableModel modelim = new DefaultTableModel();
        Object[] kolonlar = {"ID","Öğrenci Adı"};	
	Object[] satirlar = new Object[2];	
        
    Ekleme a=new Ekleme();

    private void btnBaglantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaglantiActionPerformed
        
        int dersinOgretmeni = cmb_ogretmenListele.getSelectedIndex();
        String dersinAdi = txt_ad.getText();
        String dersinKodu = txt_kod.getText();
        String dersinDersligi = txt_derslik.getText();
        a.DersEkle((dersinOgretmeni + 1), dersinAdi, dersinKodu, dersinDersligi);
    }//GEN-LAST:event_btnBaglantiActionPerformed

    private void btnOgretmenEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgretmenEkleActionPerformed
        String ogretmeninAdi = txt_OgretmenAdi.getText();
        a.OgretmenEkle(ogretmeninAdi);
    }//GEN-LAST:event_btnOgretmenEkleActionPerformed

    private void btnOgrenciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrenciEkleActionPerformed
        String ogrenciAdi = txt_OgrenciAdi.getText();
        a.OgrenciEkle(ogrenciAdi);
    }//GEN-LAST:event_btnOgrenciEkleActionPerformed

    private void btn_SinifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SinifActionPerformed
        int ders = cmb_ders.getSelectedIndex();
        int ogrenci = cmb_Ogrenci.getSelectedIndex();
        a.DersSec((ders + 1), (ogrenci + 1));
    }//GEN-LAST:event_btn_SinifActionPerformed

    private void btnDoldurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoldurActionPerformed
        try {
            cmb_ogretmenListele.removeAllItems();
            String sorgu = String.format("select * from tbl_ogretmen");
            ResultSet ekleme1 = Ekleme.dbState().executeQuery(sorgu);
            while (ekleme1.next()) {
                cmb_ogretmenListele.addItem(ekleme1.getString("OGRETMENADI"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDoldurActionPerformed

    private void btn_DoldurDersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoldurDersActionPerformed
        try {
            cmb_ders.removeAllItems();
            String sorguDers = String.format("select * from tbl_ders"); 
            ResultSet dersResult = Ekleme.dbState().executeQuery(sorguDers);
            while (dersResult.next()) {
                cmb_ders.addItem(dersResult.getString("DERSADI"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_DoldurDersActionPerformed

    private void btn_DoldurOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoldurOgrenciActionPerformed
       try {
            cmb_Ogrenci.removeAllItems();
            String sorguOgrenci = String.format("select * from tbl_ogrenci"); 
            ResultSet ogrenciResult = Ekleme.dbState().executeQuery(sorguOgrenci);
            while (ogrenciResult.next()) {
                cmb_Ogrenci.addItem(ogrenciResult.getString("OGRENCIADI"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_DoldurOgrenciActionPerformed

    private void btnRaporlamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaporlamaActionPerformed
        int ders = cmbRaporla.getSelectedIndex()+1;
        try{
            modelim.setRowCount(0);
            String sorguOgrenci = String.format("select * from tbl_ogrenci where Id in (select OGRENCIID from tbl_sinif where dersId in (select ID from tbl_ders where ID = %d))",ders); 
            ResultSet ogrenciResult = Ekleme.dbState().executeQuery(sorguOgrenci);
            tableRaporlama.setModel(modelim);
            modelim.setColumnIdentifiers(kolonlar);
            
            while(ogrenciResult.next()){
                
                satirlar[0]=ogrenciResult.getString("ID");
                satirlar[1]=ogrenciResult.getString("OGRENCIADI");
                modelim.addRow(satirlar);
                
            }
            
        }
        catch(Exception e){
            System.out.println("Tablo Eklemede Bir Hata Oluştu...");
        }
        
    }//GEN-LAST:event_btnRaporlamaActionPerformed

    private void btnDoldurTabloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoldurTabloActionPerformed
        try {
            cmbRaporla.removeAllItems();
            String sorguOgrenci = String.format("select dersAdi from tbl_ders"); 
            ResultSet ogrenciResult = Ekleme.dbState().executeQuery(sorguOgrenci);
            while (ogrenciResult.next()) {
                cmbRaporla.addItem(ogrenciResult.getString("dersAdi"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDoldurTabloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try{
//            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/db_derslik","root","1234");
//            Statement stmt=con.createStatement();
//            
//            String sorgu=String.format("select * from tbl_ogretmen");
//            int ekleme = stmt.executeUpdate(sorgu);
//            ResultSet ekleme1= stmt.executeQuery(sorgu);
//            while(ekleme1.next()){
//                cmb_ogretmenListele.addItem(ekleme1.getString("ogretmenAdi"));
//            }
//        }catch(Exception e){ System.out.println(e);}

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaglanti;
    private javax.swing.JButton btnDoldur;
    private javax.swing.JButton btnDoldurTablo;
    private javax.swing.JButton btnOgrenciEkle;
    private javax.swing.JButton btnOgretmenEkle;
    private javax.swing.JButton btnRaporlama;
    private javax.swing.JButton btn_DoldurDers;
    private javax.swing.JButton btn_DoldurOgrenci;
    private javax.swing.JButton btn_Sinif;
    private javax.swing.JComboBox cmbRaporla;
    private javax.swing.JComboBox cmb_Ogrenci;
    private javax.swing.JComboBox cmb_ders;
    private javax.swing.JComboBox cmb_ogretmenListele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableRaporlama;
    private javax.swing.JTextArea txt_OgrenciAdi;
    private javax.swing.JTextArea txt_OgretmenAdi;
    private javax.swing.JTextArea txt_ad;
    private javax.swing.JTextArea txt_derslik;
    private javax.swing.JTextArea txt_kod;
    // End of variables declaration//GEN-END:variables
}
